language: node_js
node_js:
- '0.10'
notifications:
  hipchat:
    rooms:
      secure: Tf1ztBA2iPXoQMeCXx6XgoQTatlhrCA+z6tpjS7Wh0gAzsyPLTokb0gjOwZWnwxUdiPs3QOdc7SkxWO3fnA8KnxEaEgZVUjRLo3AhkjtyW8f7Y87kPKZ+Nia2tdLrDRG/cwg2bXigfTjSPsPtdvOC7ZiJtITwZ3TW6FxzDTWu9M=
