language: node_js
node_js:
- '0.10'
notifications:
  hipchat:
    rooms:
      secure: OpwloxIZSjBDWZXp/hYOL8jUbFWEdbkhvnXT3oodRnOT9+Ldr76GA1xASOXLDpCd9pfG035PnFcLA8C5AuO76GsUWXtV/4lq/va/xNmN9ppvvSHHPi1uBSelmRFHPJ3f3URFGQffXUEsI/5q3ZYUcxB0gocLDVd2SaStTBoCXx8=
